# Generated by Django 5.0.6 on 2026-05-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_hour',
        ),
    ]
