# Generated by Django 5.2.14 on 2026-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_remove_room_capacity_remove_room_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'оплата в офисе организации'), ('card', 'оплата картой МИР'), ('qrcode', 'предоплата по QR-коду')], max_length=12, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('scheduled', 'Мероприятие назначено'), ('completed', 'Мероприятие завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
